# Generated by Django 3.0.5 on 2020-08-13 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='tz',
        ),
    ]
