# Generated by Django 3.0.5 on 2020-08-13 14:40

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_remove_member_tz'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='tz',
            field=timezone_field.fields.TimeZoneField(default='Europe/London'),
        ),
    ]
