# Generated by Django 3.0.5 on 2020-08-13 14:45

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_member_tz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='tz',
            field=timezone_field.fields.TimeZoneField(),
        ),
    ]
