# Generated by Django 3.0.5 on 2020-08-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20200813_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='tz',
            field=models.CharField(max_length=60),
        ),
    ]
